aliases:
 - default: &default
#     working_directory: ~/circleci_node_test
     parameters:
       parallelism:
         type: integer
         default: 1
     environment:
       PARALLELISM: << parameters.parallelism >>
     parallelism: << parameters.parallelism >>

executors:
  build-and-test:
    docker:
       # - image: cimg/node:8.17
       - image: cimg/node:12.18
  deploy:
    machine:
      image: ubuntu-1604:202004-01

commands:
  test:
    steps:
      - run: |
            if [[ ${PARALLELISM} == 1 ]]; then
              echo 'Runnig test in sequential ...'
              npm test
            elif [[ ${PARALLELISM} > 1 ]]; then
              echo 'Runnig test in parallel ...'
              circleci tests glob "__tests__/*.js" \
              | circleci tests split > /tmp/jest-tests && \
              npm test $(cat /tmp/jest-tests)
            fi

version: 2.1

jobs:
  qa-build-and-test:
    <<: *default
    executor:
      name: build-and-test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v3-dependency-cache-{{ .Branch }}-
      - run: npm install
      - save_cache:
          key: v3-dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - test
  build-and-test:
    <<: *default
    executor:
      name: build-and-test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependency-cache-{{ checksum "package-lock.json" }}
            - v3-dependency-cache-
      - run: npm install
      - save_cache:
          key: v3-dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - test
  deploy:
    executor:
      name: deploy
    steps:
      - checkout
      - run: sudo apt-get update
      - run: ls -al $HOME

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - qa-build-and-test:
          filters:
            branches:
              only:
                - qa
      - build-and-test:
          filters:
            branches:
              ignore:
                - qa
      - deploy:
          requires:
            - qa-build-and-test
            - build-and-test
          filters:
            branches:
              only:
                - master
                - staging
                - qa

