anchors:
  - &default
      working_directory: ~/circleci_node_test
      shell: /bin/bash --login

version: 2.1

orbs:
  node: circleci/node:8

jobs:
  build_and_test:
    <<: *default
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install-packages:
          cahce-path: ~/circleci_node_test/node_modules
          override-ci-command: npm install
      - run: echo 'all done'

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build_and_test

