#anchors:
#  - &default
#      working_directory: ~/circleci_node_test
#      shell: /bin/bash
#  - &image
#      docker:
#        - image: cimg/node:8.17

executors:
  build-and-test:
    working_directory: ~/Nextremer/minarai-application2
    docker:
       - image: cimg/node:8.17
  deploy:
    working_directory: ~/Nextremer/minarai-application2
    machine:
      image: ubuntu-1604:202004-01
version: 2.1

jobs:
  qa-build-and-test:
    executor:
      name: build-and-test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-dependency-cache-{{ .Branch }}-
      - run: npm install
      - save_cache:
          key: v1-dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: echo 'all done(qa branch)'
  build-and-test:
    executor:
      name: build-and-test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependency-cache-{{ checksum "package-lock.json" }}
            - v1-dependency-cache-
      - run: npm install
      - save_cache:
          key: v1-dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: echo 'all done(except qa branch)'
  deploy:
    executor:
      name: deploy
    steps:
      - checkout
      - run: sudo apt-get update
      - run: ls -al $HOME

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - qa-build-and-test:
          filters:
            branches:
              only:
                - qa
      - build-and-test:
          filters:
            branches:
              ignore:
                - qa
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
                - staging

