version: 2.1

commands:
  restore-cache:
    steps:
      - when:
          condition:
            equal: [ << pipeline.git.branch >>, qa ]
          steps:
            - restore_cache:
                name: Restoring cache in qa branch
                keys:
                  - v3-dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
                  - v3-dependency-cache-{{ .Branch }}-
      - unless:
          condition:
            equal: [ << pipeline.git.branch >>, qa ]
          steps:
            - restore_cache:
                name: Restoring cache in << pipeline.git.branch >> branch
                keys:
                  - v3-dependency-cache-{{ checksum "package-lock.json" }}
                  - v3-dependency-cache-
  save-cache:
    steps:
      - when:
          condition:
            equal: [ << pipeline.git.branch >>, qa ]
          steps:
            - save_cache:
                name: Saving cache in qa branch
                key: v3-dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
                paths:
                  - ./node_modules
      - unless:
          condition:
            equal: [ << pipeline.git.branch >>, qa ]
          steps:
            - save_cache:
                name: Saving cache in << pipeline.git.branch >> branch
                key: v3-dependency-cache-{{ checksum "package-lock.json" }}
                paths:
                  - ./node_modules
  test:
    parameters:
      parallelism:
        type: integer
    steps:
      - when:
          condition:
            equal: [ << parameters.parallelism >>, 1 ]
          steps:
            - run:
                name: Run test in sequence
                command: npm test
      - unless:
          condition:
            equal: [ << parameters.parallelism >>, 1 ]
          steps:
            - run:
                name: Run test in parallel
                command: |
                  circleci tests glob "__tests__/*.js" \
                    | circleci tests split --split-by=timings > /tmp/jest-tests
                  npm test $(cat /tmp/jest-tests)

jobs:
  build-and-test:
    parameters:
      parallelism:
        type: integer
        default: 1
    parallelism: << parameters.parallelism >>
    docker:
       # - image: cimg/node:8.17
       - image: cimg/node:12.18
       - image: circleci/mysql:5.7
         environment:
           MYSQL_ALLOW_EMPTY_PASSWORD: yes
           MYSQL_USER: circleci
       - image: circleci/redis:3.2
       - image: circleci/mongo:3.6
    steps:
      - checkout
      - restore-cache
      - run: npm install
      - save-cache
      - run:
          name: Wait for connections
          command: |
            dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
            dockerize -wait tcp://127.0.0.1:6379 -timeout 1m
            dockerize -wait tcp://127.0.0.1:27017 -timeout 1m
      - run:
          name: mysql
          command: |
            sudo apt-get update &&
            sudo apt-get install default-mysql-client
            mysql -h 127.0.0.1 -u root -e 'select host,user from mysql.user;'
      - test:
          parallelism: << parameters.parallelism >>
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
      - store_artifacts:
          path: coverage
      - run: npm start
  deploy:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run: sudo apt-get update

workflows:
  build-test-and-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
                - staging
                - qa

