anchors:
  - &default
      working_directory: ~/circleci_node_test
      shell: /bin/bash --login
  - &image
      docker:
        - image: cimg/node:8.17

version: 2.1

jobs:
  build_and_test:
    <<: *default
    <<: *image
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: node --version

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build_and_test
