version: 2.1

aliases:
 - default: &default
     # working_directory: ~/circleci_node_test
     parameters:
       parallelism:
         type: integer
         default: 3
     parallelism: << parameters.parallelism >>

executors:
  build-and-test:
    docker:
       # - image: cimg/node:8.17
       - image: cimg/node:12.18
  deploy:
    machine:
      image: ubuntu-1604:202004-01

commands:
  test:
    parameters:
      parallelism:
        type: env_var_name
        default: parallelism
    steps:
      - run: echo ${<< parameters.parallelism >>}
      - when:
          condition:
            equal: [ << parameters.parallelism >>, 1 ]
          steps:
            - run:
                name: "Run test in sequential"
                command: npm test
      - unless:
          condition:
            equal: [ << parameters.parallelism >>, 1 ]
          steps:
            - run:
                name: "Run test in parallel"
                command: |
                  circleci tests glob "__tests__/*.js" \
                    | circleci tests split > /tmp/jest-tests
                  npm test $(cat /tmp/jest-tests)

jobs:
  build-and-test:
    <<: *default
    executor:
      name: build-and-test
    steps:
      - checkout
      - when:
          condition:
            equal: [ << pipeline.git.branch >>, qa ]
          steps:
            - restore_cache:
                keys:
                  - v3-dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
                  - v3-dependency-cache-{{ .Branch }}-
            - run: npm install
            - save_cache:
                key: v3-dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
                paths:
                  - ./node_modules
      - unless:
          condition:
            equal: [ << pipeline.git.branch >>, qa ]
          steps:
            - restore_cache:
                keys:
                  - v3-dependency-cache-{{ checksum "package-lock.json" }}
                  - v3-dependency-cache-
            - run: npm install
            - save_cache:
                key: v3-dependency-cache-{{ checksum "package-lock.json" }}
                paths:
                  - ./node_modules
      - when:
          condition:
            equal: [ << parameters.parallelism >>, 1 ]
          steps:
            - run:
                name: "Run test in sequential"
                command: npm test
      - unless:
          condition:
            equal: [ << parameters.parallelism >>, 1 ]
          steps:
            - run:
                name: "Run test in parallel"
                command: |
                  circleci tests glob "__tests__/*.js" \
                    | circleci tests split > /tmp/jest-tests
                  npm test $(cat /tmp/jest-tests)
  deploy:
    executor:
      name: deploy
    steps:
      - checkout
      - run: sudo apt-get update
      - run: ls -al $HOME

workflows:
  build-test-and-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
                - staging
                - qa

