version: 2.1

orbs:
  node: circleci/node@4.0.0

jobs:
  build_and_test:
    shell: /bin/bash --login
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: echo 'all done'

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build_and_test

